### ISSUE TITLE
License unknown

### ISSUE THREAD

**Issue by tGeorgeDN** [knezzz/ntp#1]
Hi,
first I have to say that your package works great and we are happy to have come across it!!
We from Diebold Nixdorf would like to use it in a cross-plattform app, implemented in Flutter and therefore would need a license statement.

Could you please update the file https://github.com/knezzz/ntp/blob/master/LICENSE ?
Since many Dart packages are under BSD license, does it apply to this package as well?

**Comment by knezzz** [comment]
Added!
