### ISSUE TITLE
How to Handle SocketException: Failed host lookup: 'pool.ntp.org' ?

### ISSUE THREAD

**Issue by yusrenaltair** [knezzz/ntp#10]
I tried your package and tested "What if the internet connection suddenly lost?"
And the result :
```Exception has occurred.
SocketException (SocketException: Failed host lookup: 'pool.ntp.org'
(OS Error: No address associated with hostname, errno = 7))
```
I want to know how to handle this problem?
Thanks a lot.

**Comment by knezzz** [comment]
Hmm, well for now I think easiest thing would be to either wrap the call with try/catch or make your logic before making NTP call. But I was thinking of rewriting this a bit to make it easier to use and more robust, so if you make any changes feel free to make PR :)

**Comment by yusrenaltair** [comment]
I currently use a connectivity 0.4.6+2 package to monitor the network. The results are quite satisfying.
Thanks
