### ISSUE TITLE
Destination Timestamp is the same as Originate Timestamp in _parseData(List<int> data, DateTime time)

### ISSUE THREAD

**Issue by alien190** [knezzz/ntp#25]
RFC 2030 https://tools.ietf.org/html/rfc2030  page 11-12

> To calculate the roundtrip delay d and local clock offset t relative
>  to the server, the client sets the transmit timestamp in the request
>  to the time of day according to the client clock in NTP timestamp
>   format. The server copies this field to the originate timestamp in
>   the reply and sets the receive timestamp and transmit timestamp to
>   the time of day according to the server clock in NTP timestamp
>   format.
>   When the server reply is received, the client determines a
>  Destination Timestamp variable as the time of arrival according to
>   its clock in NTP timestamp format. The following table summarizes the
>   four timestamps.

>  Timestamp Name          ID   When Generated
>      ------------------------------------------------------------
>      Originate Timestamp     T1   time request sent by client
>      Receive Timestamp       T2   time request received by server
>      Transmit Timestamp      T3   time reply sent by server
>      Destination Timestamp   T4   time reply received by client
>
> 
>   The roundtrip delay d and local clock offset t are defined as
>
>     d = (T4 - T1) - (T2 - T3)     t = ((T2 - T1) + (T3 - T4)) / 2.

But in the NTP offset calculation the same timestamp are using as Originate Timestamp (T1) and Destination Timestamp (T4)

`static Future<int> getNtpOffset({String lookUpAddress = 'pool.ntp.org', int port = 123, DateTime localTime}) async {`
......
` final DateTime time = localTime ?? DateTime.now();`
`_ntpMessage.encodeTimestamp(buffer, 40, (time.millisecondsSinceEpoch / 1000.0) + _ntpMessage.timeToUtc);`
....
`final int offset = _parseData(packet.data, time);`
`return offset;`
`}`

`static int _parseData(List<int> data, DateTime time) {`
`    final _NTPMessage _ntpMessage = _NTPMessage(data);`
`    final double destinationTimestamp = (time.millisecondsSinceEpoch / 1000.0) + 2208988800.0;`
`   final double localClockOffset = ((_ntpMessage._receiveTimestamp - _ntpMessage._originateTimestamp) +`
`            (_ntpMessage._transmitTimestamp - destinationTimestamp)) /`
`        2;`
``
`   return (localClockOffset * 1000).toInt();`
`  }`

Does It have some reasons?

**Comment by knezzz** [comment]
Forgot to comment, but yeah there was no reason, it was a bug, really nice that you spotted it and reported 😃. Now lib has much better performance (before it was ~100ms off, now it's ~10ms)

Fix is available in 1.0.8 version 

Thanks for reporting 😄
