### ISSUE TITLE
In one instance NTP.now() returned (Monday, January 1, 1900 12:00:01) (-2208988798384)

### ISSUE THREAD

**Issue by ganeshp0001** [knezzz/ntp#26]
Thank you for this great package :)

We have used NTP packaged in one of our app to capture start / end time for the sessions.
In one instance time captured was
(Monday, January 1, 1900 12:00:01) (-2208988798384)

I am not sure how or what is the issue. Can you please provide some details how this could have happened. I can not say I am able to recreate it, but the time captured is received from NTP.now().

**Comment by knezzz** [comment]
Hey, Hmm that is weird, If you manage to somehow recreate the issue that would be really helpful.
For now I would suggest using another `lookUpAddress`.

ex. 
Google NTP - time.google.com 
Or there is huge list of available servers [here](https://gist.github.com/mutin-sa/eea1c396b1e610a2da1e5550d94b0453)
By default lib is using `pool.ntp.org` that is run by volunteers

**Comment by ganeshp0001** [comment]
Thanks for the reply. 

Yes, it's weird indeed. I could not recreate the issue as the app had been under development for the last 7-8 months and we never saw any such date/value returned by NTP. Right now the app is being used by around 500+ users on the iOS & Android platforms. And it happened only once so far. Maybe I will try to contact the actual user to get information about his device if it will help me to recreate the issue.

I just did some research and was wondering if any of the server run by volunteers, is not properly set up, could it return this value/date as default date? Or if any such issue had been reported to you in past.

Right now, I have implemented the approach you subjected, and it's working perfectly. 👍 

Since its not an actual issue with your package, I  am marking it as closed. 

Have a great day!

**Comment by knezzz** [comment]
Okay great 😄 

Not sure how exactly pool.ntp works, but it could be possible that some server is not properly setup or had some issues at exact time the request was made. That would also explain the inability to recreate the issue.

Thanks! You too 😄
