### ISSUE TITLE
Publish null-safety version on pub.dev

### ISSUE THREAD

**Issue by zeshuaro** [knezzz/ntp#33]
Can we have the null-safety version published on pub.dev? I'm using this package for another package and this is the only one left that hasn't been migrated to null-safety.

**Comment by yanivshaked** [comment]
@knezzz Any estimation on when will a new version be ready? (I see null safety was already merged)

**Comment by knezzz** [comment]
Hey yeah sorry, I have few things I want to test before, I'll try to push update this weekend

**Comment by BWhiteApps** [comment]
@knezzz will there be an update this weekend? We are currently migrating our project and this is the last package we are waiting on.

**Comment by knezzz** [comment]
Hey, sorry for delay. I published it now and version `2.0.0` is null safe :)
