### ISSUE TITLE
What is the difference between using `NTP.now()` or adding offset to `DateTime.now()`

### ISSUE THREAD

**Issue by comatory** [knezzz/ntp#39]
So I don't understand what is the difference between this:

```dart
final now = DateTime.now();
final offset = await NTP.getNtpOffset(localTime: now);
final accurateNow = now.add(Duration(milliseconds: offset);
```

and

```dart
final accurateNow = await NTP.now();
```

Can this approach be used interchangeably?

**Comment by knezzz** [comment]
Hi,

No difference, NTP.now is just a helper function so you can get time in one line instead of 3 :) 

Here is code for NTP.now: https://github.com/knezzz/ntp/blob/59794add1157cceb2d96e63f92f76265925b22e8/lib/ntp/ntp.dart#L68-L83

Closing this
