### ISSUE TITLE
How can I get my country time?

### ISSUE THREAD

**Issue by NTMS2017** [knezzz/ntp#6]
I need to get my country time, so how can I change String lookUpAddress: 'pool.ntp.org', so gets my country time? Thanks

**Comment by knezzz** [comment]
Hi,

You can use this method to get current ntp time, this will return your local time with ntp offset, so this time will be same on every device (maybe ~50ms difference):

```dart
    final DateTime ntpTime = await NTP.now();
```

and you can change lookup address by passing a new address like this:
```dart
int _offset = await NTP.getNtpOffset(lookUpAddress: 'some.new.address');
```

But pool.ntp.org is most widely used and it is available everywhere

**Comment by NTMS2017** [comment]
thank you.
