### ISSUE TITLE
time is about 1 second off between clients

### ISSUE THREAD

**Issue by jimgreer** [knezzz/ntp#8]
I'm using NTP to synchronize audio playback across multiple mobile devices, so I need it to be quite accurate. 

I notice that there's a little less than 1 second difference across the devices. Is it possible to make this more accurate?

I know that the NTP protocol requires approximately fifteen minutes to settle, but it looks like this implementation relies on a single message to an NTP server. Could that account for the difference?

This is per the ntp.org docs, if I'm reading them correctly:

> When the ntpd is started and the file does not exist, the ntpd enters a special mode designed to quickly adapt to the particular system clock oscillator time and frequency error. This takes approximately 15 minutes, after which the time and frequency are set to nominal values and the ntpd enters normal mode, where the time and frequency are continuously tracked relative to the server.

**Comment by jimgreer** [comment]
I've decided to use system time for my application.

**Comment by knezzz** [comment]
Hi @jimgreer,

I was on vacation so I couldn't respond sooner. I think that 15min is for server to settle maybe? I'm using this in my app where margin of error needs to be in ~25ms and it is working on every device I have tested. I could send you that code. Ill probably add it to example in this lib.

**Comment by jimgreer** [comment]
Thanks Luka. I was ignorant of the settle time for NTP, and trying to use
it on a Flutter mobile app that needed sync much quicker. I realized that
the system time is adequate for my needs.

You can close this issue.
