### ISSUE TITLE
getNTPOffset gets stuck

### ISSUE THREAD

**Issue by samuelsarix** [knezzz/ntp#9]
When i use getNTPOffset it sometimes gets stuck at await _datagramSocket.firstWhere

**Comment by samuelsarix** [comment]
I sent too many requests

**Comment by pav3lo** [comment]
Sometimes it get stuck, why?

**Comment by knezzz** [comment]
@pav3lo Do you have some minimal code example where this error occurs?

**Comment by pav3lo** [comment]
When i run this from main, sometimes it gets freeze: 
 print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));
  print(await NTP.getNtpOffset(localTime: DateTime.now()));

**Comment by knezzz** [comment]
From [NTP pool website](https://www.ntppool.org/en/use.html):
> Many servers are provided by volunteers, and almost all time servers are really file or mail or webservers which just happen to also run ntp. **So don't use more than four time servers in your configuration**, and don't play tricks with burst or minpoll - all you will gain is extra load on the volunteer time servers.

You are not supposed to use it like that, you should call it only once (initialization of the app) save it, and then load it if you need it again. 
Try not to call it that frequently, or change ntp server to some other that might handle that (like maybe `time.google.com`). But I think eventually they will start timeouting you as well.

To get NTP from different server: 
```dart
NTP.getNtpOffset(lookupAddress: 'time.google.com');
```
